workflows:
  sshx-macos:
    name: "SSHX on macOS"
    scripts:
      - name: Run SSHX with nohup + spam df -h
        script: |
          set -euo pipefail
          LOG_DIR="$HOME/sshx-logs"
          mkdir -p "$LOG_DIR"

          SSHX_LOG="$LOG_DIR/sshx.log"
          DF_LOG="$LOG_DIR/df-h.log"

          echo "=== Running SSHX with nohup ==="
          nohup sh -c 'curl -sSf https://sshx.io/get | sh -s run' >> "$SSHX_LOG" 2>&1 &

          echo "=== Showing SSHX log ==="
          cat "$SSHX_LOG" &

          echo "=== Spamming df -h ==="
          while true; do date +"%Y-%m-%d %H:%M:%S"; df -h; echo "----"; sleep 1; done >> "$DF_LOG" 2>&1 &
